// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdxibjlkaguoeghczyzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkeGliamxrYWd1b2VnaGN6eXp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTQ2MDIsImV4cCI6MjA2NzEzMDYwMn0.IqNOpVOtRFVZa0Q0YeCHvUox7R1cplahEuHU4c9beJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});